create table notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title text not null,
    modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    folderId INTEGER REFERENCES folders(id) ON DELETE CASCADE NOT NULL,
    content text
);