create table notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_name text not null,
    modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    folderid INTEGER REFERENCES folders(id) ON DELETE CASCADE NOT NULL,
    content text
);